window.esdocSearchIndex = [
  [
    "drawvector/src/tool.js~drawtool",
    "class/src/Tool.js~DrawTool.html",
    "<span>DrawTool</span> <span class=\"search-result-import-path\">DrawVector/src/Tool.js</span>",
    "class"
  ],
  [
    "drawvector/src/node.js~node",
    "class/src/Node.js~Node.html",
    "<span>Node</span> <span class=\"search-result-import-path\">DrawVector/src/Node.js</span>",
    "class"
  ],
  [
    "drawvector/src/nodecontroller.js~nodecontroller",
    "class/src/NodeController.js~NodeController.html",
    "<span>NodeController</span> <span class=\"search-result-import-path\">DrawVector/src/NodeController.js</span>",
    "class"
  ],
  [
    "drawvector/src/path.js~path",
    "class/src/Path.js~Path.html",
    "<span>Path</span> <span class=\"search-result-import-path\">DrawVector/src/Path.js</span>",
    "class"
  ],
  [
    "drawvector/src/tool.js~selecttool",
    "class/src/Tool.js~SelectTool.html",
    "<span>SelectTool</span> <span class=\"search-result-import-path\">DrawVector/src/Tool.js</span>",
    "class"
  ],
  [
    "drawvector/src/tool.js~tool",
    "class/src/Tool.js~Tool.html",
    "<span>Tool</span> <span class=\"search-result-import-path\">DrawVector/src/Tool.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/node.js",
    "file/src/Node.js.html",
    "src/Node.js",
    "file"
  ],
  [
    "src/node.js~node#center",
    "class/src/Node.js~Node.html#instance-member-center",
    "src/Node.js~Node#center",
    "member"
  ],
  [
    "src/node.js~node#constructor",
    "class/src/Node.js~Node.html#instance-constructor-constructor",
    "src/Node.js~Node#constructor",
    "method"
  ],
  [
    "src/node.js~node#key",
    "class/src/Node.js~Node.html#instance-member-key",
    "src/Node.js~Node#key",
    "member"
  ],
  [
    "src/node.js~node#makenode",
    "class/src/Node.js~Node.html#instance-method-makeNode",
    "src/Node.js~Node#makeNode",
    "method"
  ],
  [
    "src/node.js~node#makerect",
    "class/src/Node.js~Node.html#instance-method-makeRect",
    "src/Node.js~Node#makeRect",
    "method"
  ],
  [
    "src/node.js~node#moveto",
    "class/src/Node.js~Node.html#instance-method-moveTo",
    "src/Node.js~Node#moveTo",
    "method"
  ],
  [
    "src/node.js~node#parent",
    "class/src/Node.js~Node.html#instance-member-parent",
    "src/Node.js~Node#parent",
    "member"
  ],
  [
    "src/node.js~node#selected",
    "class/src/Node.js~Node.html#instance-member-selected",
    "src/Node.js~Node#selected",
    "member"
  ],
  [
    "src/node.js~node#setparent",
    "class/src/Node.js~Node.html#instance-method-setParent",
    "src/Node.js~Node#setParent",
    "method"
  ],
  [
    "src/node.js~node#setselected",
    "class/src/Node.js~Node.html#instance-method-setSelected",
    "src/Node.js~Node#setSelected",
    "method"
  ],
  [
    "src/node.js~node#target",
    "class/src/Node.js~Node.html#instance-member-target",
    "src/Node.js~Node#target",
    "member"
  ],
  [
    "src/node.js~node#toggleselected",
    "class/src/Node.js~Node.html#instance-method-toggleSelected",
    "src/Node.js~Node#toggleSelected",
    "method"
  ],
  [
    "src/node.js~node#type",
    "class/src/Node.js~Node.html#instance-member-type",
    "src/Node.js~Node#type",
    "member"
  ],
  [
    "src/node.js~node#updatebesidesegment",
    "class/src/Node.js~Node.html#instance-method-updateBesideSegment",
    "src/Node.js~Node#updateBesideSegment",
    "method"
  ],
  [
    "src/node.js~node#view",
    "class/src/Node.js~Node.html#instance-member-view",
    "src/Node.js~Node#view",
    "member"
  ],
  [
    "src/nodecontroller.js",
    "file/src/NodeController.js.html",
    "src/NodeController.js",
    "file"
  ],
  [
    "src/nodecontroller.js~nodecontroller#cleanselectednodes",
    "class/src/NodeController.js~NodeController.html#instance-method-cleanSelectedNodes",
    "src/NodeController.js~NodeController#cleanSelectedNodes",
    "method"
  ],
  [
    "src/nodecontroller.js~nodecontroller#constructor",
    "class/src/NodeController.js~NodeController.html#instance-constructor-constructor",
    "src/NodeController.js~NodeController#constructor",
    "method"
  ],
  [
    "src/nodecontroller.js~nodecontroller#doubletapnode",
    "class/src/NodeController.js~NodeController.html#instance-method-doubleTapNode",
    "src/NodeController.js~NodeController#doubleTapNode",
    "method"
  ],
  [
    "src/nodecontroller.js~nodecontroller#dragnode",
    "class/src/NodeController.js~NodeController.html#instance-method-dragNode",
    "src/NodeController.js~NodeController#dragNode",
    "method"
  ],
  [
    "src/nodecontroller.js~nodecontroller#getkey",
    "class/src/NodeController.js~NodeController.html#instance-method-getKey",
    "src/NodeController.js~NodeController#getKey",
    "method"
  ],
  [
    "src/nodecontroller.js~nodecontroller#getnode",
    "class/src/NodeController.js~NodeController.html#instance-method-getNode",
    "src/NodeController.js~NodeController#getNode",
    "method"
  ],
  [
    "src/nodecontroller.js~nodecontroller#idindex",
    "class/src/NodeController.js~NodeController.html#instance-member-idIndex",
    "src/NodeController.js~NodeController#idIndex",
    "member"
  ],
  [
    "src/nodecontroller.js~nodecontroller#nodemap",
    "class/src/NodeController.js~NodeController.html#instance-member-nodeMap",
    "src/NodeController.js~NodeController#nodeMap",
    "member"
  ],
  [
    "src/nodecontroller.js~nodecontroller#pathindex",
    "class/src/NodeController.js~NodeController.html#instance-member-pathIndex",
    "src/NodeController.js~NodeController#pathIndex",
    "member"
  ],
  [
    "src/nodecontroller.js~nodecontroller#positionondrawingpanel",
    "class/src/NodeController.js~NodeController.html#instance-method-positionOnDrawingPanel",
    "src/NodeController.js~NodeController#positionOnDrawingPanel",
    "method"
  ],
  [
    "src/nodecontroller.js~nodecontroller#selectednodes",
    "class/src/NodeController.js~NodeController.html#instance-member-selectedNodes",
    "src/NodeController.js~NodeController#selectedNodes",
    "member"
  ],
  [
    "src/nodecontroller.js~nodecontroller#setlistener",
    "class/src/NodeController.js~NodeController.html#instance-method-setListener",
    "src/NodeController.js~NodeController#setListener",
    "method"
  ],
  [
    "src/nodecontroller.js~nodecontroller#tapbackground",
    "class/src/NodeController.js~NodeController.html#instance-method-tapBackground",
    "src/NodeController.js~NodeController#tapBackground",
    "method"
  ],
  [
    "src/nodecontroller.js~nodecontroller#tapnode",
    "class/src/NodeController.js~NodeController.html#instance-method-tapNode",
    "src/NodeController.js~NodeController#tapNode",
    "method"
  ],
  [
    "src/nodecontroller.js~nodecontroller#target",
    "class/src/NodeController.js~NodeController.html#instance-member-target",
    "src/NodeController.js~NodeController#target",
    "member"
  ],
  [
    "src/nodecontroller.js~nodecontroller#tool",
    "class/src/NodeController.js~NodeController.html#instance-member-tool",
    "src/NodeController.js~NodeController#tool",
    "member"
  ],
  [
    "src/path.js",
    "file/src/Path.js.html",
    "src/Path.js",
    "file"
  ],
  [
    "src/path.js~path#addnode",
    "class/src/Path.js~Path.html#instance-method-addNode",
    "src/Path.js~Path#addNode",
    "method"
  ],
  [
    "src/path.js~path#clearselected",
    "class/src/Path.js~Path.html#instance-method-clearSelected",
    "src/Path.js~Path#clearSelected",
    "method"
  ],
  [
    "src/path.js~path#closepath",
    "class/src/Path.js~Path.html#instance-method-closePath",
    "src/Path.js~Path#closePath",
    "method"
  ],
  [
    "src/path.js~path#closed",
    "class/src/Path.js~Path.html#instance-member-closed",
    "src/Path.js~Path#closed",
    "member"
  ],
  [
    "src/path.js~path#constructor",
    "class/src/Path.js~Path.html#instance-constructor-constructor",
    "src/Path.js~Path#constructor",
    "method"
  ],
  [
    "src/path.js~path#drawlinesegment",
    "class/src/Path.js~Path.html#instance-method-drawLineSegment",
    "src/Path.js~Path#drawLineSegment",
    "method"
  ],
  [
    "src/path.js~path#drawpath",
    "class/src/Path.js~Path.html#instance-method-drawPath",
    "src/Path.js~Path#drawPath",
    "method"
  ],
  [
    "src/path.js~path#firstnode",
    "class/src/Path.js~Path.html#instance-method-firstNode",
    "src/Path.js~Path#firstNode",
    "method"
  ],
  [
    "src/path.js~path#key",
    "class/src/Path.js~Path.html#instance-member-key",
    "src/Path.js~Path#key",
    "member"
  ],
  [
    "src/path.js~path#lastnode",
    "class/src/Path.js~Path.html#instance-method-lastNode",
    "src/Path.js~Path#lastNode",
    "method"
  ],
  [
    "src/path.js~path#makelinedescript",
    "class/src/Path.js~Path.html#instance-method-makeLineDescript",
    "src/Path.js~Path#makeLineDescript",
    "method"
  ],
  [
    "src/path.js~path#makepathdescription",
    "class/src/Path.js~Path.html#instance-method-makePathDescription",
    "src/Path.js~Path#makePathDescription",
    "method"
  ],
  [
    "src/path.js~path#nosegment",
    "class/src/Path.js~Path.html#instance-method-noSegment",
    "src/Path.js~Path#noSegment",
    "method"
  ],
  [
    "src/path.js~path#nodes",
    "class/src/Path.js~Path.html#instance-member-nodes",
    "src/Path.js~Path#nodes",
    "member"
  ],
  [
    "src/path.js~path#segmnetmap",
    "class/src/Path.js~Path.html#instance-member-segmnetMap",
    "src/Path.js~Path#segmnetMap",
    "member"
  ],
  [
    "src/path.js~path#target",
    "class/src/Path.js~Path.html#instance-member-target",
    "src/Path.js~Path#target",
    "member"
  ],
  [
    "src/path.js~path#updatepresentsegment",
    "class/src/Path.js~Path.html#instance-method-updatePresentSegment",
    "src/Path.js~Path#updatePresentSegment",
    "method"
  ],
  [
    "src/path.js~path#updateprevsegment",
    "class/src/Path.js~Path.html#instance-method-updatePrevSegment",
    "src/Path.js~Path#updatePrevSegment",
    "method"
  ],
  [
    "src/path.js~path#updatesegment",
    "class/src/Path.js~Path.html#instance-method-updateSegment",
    "src/Path.js~Path#updateSegment",
    "method"
  ],
  [
    "src/tool.js",
    "file/src/Tool.js.html",
    "src/Tool.js",
    "file"
  ],
  [
    "src/tool.js~drawtool#addnodetohandle",
    "class/src/Tool.js~DrawTool.html#instance-method-addNodeToHandle",
    "src/Tool.js~DrawTool#addNodeToHandle",
    "method"
  ],
  [
    "src/tool.js~drawtool#constructor",
    "class/src/Tool.js~DrawTool.html#instance-constructor-constructor",
    "src/Tool.js~DrawTool#constructor",
    "method"
  ],
  [
    "src/tool.js~drawtool#handle",
    "class/src/Tool.js~DrawTool.html#instance-member-handle",
    "src/Tool.js~DrawTool#handle",
    "member"
  ],
  [
    "src/tool.js~drawtool#makelinenode",
    "class/src/Tool.js~DrawTool.html#instance-method-makeLineNode",
    "src/Tool.js~DrawTool#makeLineNode",
    "method"
  ],
  [
    "src/tool.js~drawtool#makepath",
    "class/src/Tool.js~DrawTool.html#instance-method-makePath",
    "src/Tool.js~DrawTool#makePath",
    "method"
  ],
  [
    "src/tool.js~drawtool#tapbackground",
    "class/src/Tool.js~DrawTool.html#instance-method-tapBackground",
    "src/Tool.js~DrawTool#tapBackground",
    "method"
  ],
  [
    "src/tool.js~drawtool#tapnode",
    "class/src/Tool.js~DrawTool.html#instance-method-tapNode",
    "src/Tool.js~DrawTool#tapNode",
    "method"
  ],
  [
    "src/tool.js~selecttool#doubletapnode",
    "class/src/Tool.js~SelectTool.html#instance-method-doubleTapNode",
    "src/Tool.js~SelectTool#doubleTapNode",
    "method"
  ],
  [
    "src/tool.js~selecttool#dragnode",
    "class/src/Tool.js~SelectTool.html#instance-method-dragNode",
    "src/Tool.js~SelectTool#dragNode",
    "method"
  ],
  [
    "src/tool.js~selecttool#tapbackground",
    "class/src/Tool.js~SelectTool.html#instance-method-tapBackground",
    "src/Tool.js~SelectTool#tapBackground",
    "method"
  ],
  [
    "src/tool.js~selecttool#tapnode",
    "class/src/Tool.js~SelectTool.html#instance-method-tapNode",
    "src/Tool.js~SelectTool#tapNode",
    "method"
  ],
  [
    "src/tool.js~tool#constructor",
    "class/src/Tool.js~Tool.html#instance-constructor-constructor",
    "src/Tool.js~Tool#constructor",
    "method"
  ],
  [
    "src/tool.js~tool#delegate",
    "class/src/Tool.js~Tool.html#instance-member-delegate",
    "src/Tool.js~Tool#delegate",
    "member"
  ],
  [
    "src/tool.js~tool#doubletapnode",
    "class/src/Tool.js~Tool.html#instance-method-doubleTapNode",
    "src/Tool.js~Tool#doubleTapNode",
    "method"
  ],
  [
    "src/tool.js~tool#dragnode",
    "class/src/Tool.js~Tool.html#instance-method-dragNode",
    "src/Tool.js~Tool#dragNode",
    "method"
  ],
  [
    "src/tool.js~tool#setdelegate",
    "class/src/Tool.js~Tool.html#instance-method-setDelegate",
    "src/Tool.js~Tool#setDelegate",
    "method"
  ],
  [
    "src/tool.js~tool#tapbackground",
    "class/src/Tool.js~Tool.html#instance-method-tapBackground",
    "src/Tool.js~Tool#tapBackground",
    "method"
  ],
  [
    "src/tool.js~tool#tapnode",
    "class/src/Tool.js~Tool.html#instance-method-tapNode",
    "src/Tool.js~Tool#tapNode",
    "method"
  ],
  [
    "src/main.js",
    "file/src/main.js.html",
    "src/main.js",
    "file"
  ]
]